name: Build zhengchen-minicam

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build zhengchen-minicam
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v5.5.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build
        run: |
          . /opt/esp-idf/export.sh
          idf.py set-target esp32s3
          idf.py -D BOARD=zhengchen-minicam build

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: xiaozhi_zhengchen_minicam
          path: build/merged-binary.bin
          if-no-files-found: error