name: Upstream IDF 5.5.4

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v5.5.4
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build
        run: |
          . $IDF_PATH/export.sh
          idf.py set-target esp32s3 2>&1
          idf.py -DBOARD_NAME=esp-box -DBOARD_TYPE=esp-box build 2>&1
          echo "BUILD_DONE"
